"""Relaxed MXene slab structures and descriptors derived from them.

Every quantity in `StructureDescriptors` is computed from the relaxed
structure alone (no additional simulation), so it can be regenerated by any
user from the stored structure with `StructureDescriptors.from_structure`.

All structures are periodic slab models: the sheet lies in the plane spanned
by lattice vectors a and b, and lattice vector c points along the surface
normal (z) with vacuum separating periodic images.
"""

from __future__ import annotations

from functools import cached_property
from itertools import product

import numpy as np
from emmet.core.math import Matrix3D, Vector3D
from pydantic import BaseModel, ConfigDict, Field, model_validator
from pymatgen.core import Element, Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

_MODEL_CONFIG = ConfigDict(extra="forbid", allow_inf_nan=False)

# 1 amu / Å^2 expressed in mg / m^2
_AMU_PER_A2_TO_MG_PER_M2 = 1.66053906660e-27 * 1e6 / 1e-20

LAYER_Z_TOLERANCE = 0.4
"""Atoms whose z coordinates differ by less than this (Å) share a layer."""

ECLIPSED_XY_TOLERANCE = 0.5
"""Layers whose in-plane positions coincide within this (Å) are eclipsed."""

SYMPREC = 0.1
"""Symmetry tolerance (Å) passed to spglib."""


def _is_metal(symbol: str) -> bool:
    return Element(symbol).is_transition_metal


def plain_formula(composition) -> str:
    """Reduced formula in M, X, T order without grouping, e.g. `Hf3C2F2`.

    pymatgen's `reduced_formula` may group elements (`Hf3(CF)2`), which is
    harder to search for; here elements are ordered by electronegativity.
    """
    reduced = composition.reduced_composition
    parts = []
    for el in sorted(reduced, key=lambda e: e.X):
        amount = round(reduced[el])
        parts.append(f"{el.symbol}{amount if amount != 1 else ''}")
    return "".join(parts)


class MXeneStructure(BaseModel):
    """Relaxed slab structure, stored in an Arrow/Parquet-friendly form."""

    model_config = _MODEL_CONFIG

    lattice: Matrix3D = Field(
        description="3x3 matrix of lattice vectors in Å; rows are a, b, c. "
        "a and b lie in the plane of the sheet and c spans the sheet plus vacuum.",
    )
    species: list[str] = Field(
        description="Element symbol of each site, in the same order as `fracCoords`.",
    )
    fracCoords: list[Vector3D] = Field(
        description="Fractional coordinates of each site with respect to `lattice`.",
    )

    @model_validator(mode="after")
    def _check_structure(self) -> MXeneStructure:
        if len(self.species) != len(self.fracCoords):
            raise ValueError("species and fracCoords must have the same length")
        for symbol in self.species:
            Element(symbol)
        lattice = np.array(self.lattice)
        if not np.allclose(lattice[:2, 2], 0.0, atol=1e-4):
            raise ValueError(
                "Lattice vectors a and b must lie in the xy plane (sheet plane)"
            )
        return self

    @classmethod
    def from_structure(cls, structure: Structure) -> MXeneStructure:
        """Build from a pymatgen `Structure` (e.g. read from a CONTCAR)."""
        return cls(
            lattice=structure.lattice.matrix.tolist(),
            species=[site.specie.symbol for site in structure],
            fracCoords=structure.frac_coords.tolist(),
        )

    @cached_property
    def pymatgen_structure(self) -> Structure:
        """Return the structure as a pymatgen `Structure`."""
        return Structure(self.lattice, self.species, self.fracCoords)


class StructureDescriptors(BaseModel):
    """Geometric descriptors computed directly from the relaxed structure."""

    model_config = _MODEL_CONFIG

    reducedFormula: str = Field(
        description="Reduced chemical formula of the slab in M, X, T order, "
        "e.g. `Hf2CF2` or `Ti3C2O2`.",
    )
    nSites: int = Field(description="Number of sites in the simulation cell.")
    a: float = Field(description="Length of in-plane lattice vector a, in Å.")
    b: float = Field(description="Length of in-plane lattice vector b, in Å.")
    gamma: float = Field(
        description="Angle between in-plane lattice vectors a and b, in degrees.",
    )
    cellArea: float = Field(
        description="In-plane area of the simulation cell |a x b|, in Å^2.",
    )
    areaPerFormulaUnit: float = Field(
        description="In-plane area per M_{n+1}X_nT_x formula unit, in Å^2.",
    )
    arealMassDensity: float = Field(
        description="Mass per unit sheet area, in mg/m^2.",
    )
    thickness: float = Field(
        description="Distance along z between the lowest and highest atomic "
        "nuclei of the sheet, in Å (does not include atomic radii).",
    )
    vacuum: float = Field(
        description="Vacuum gap between periodic images of the sheet along z, "
        "in Å (cell height along the normal minus `thickness`).",
    )
    layerSequence: list[str] = Field(
        description="Element of each atomic layer from bottom to top, "
        "e.g. [`F`, `Hf`, `C`, `Hf`, `F`].",
    )
    coordinationSequence: list[str] = Field(
        description="Coordination of each interior layer from bottom to top: "
        "`O` (octahedral) if the layers directly below and above it are "
        "staggered, `P` (trigonal prismatic) if they are eclipsed. The first "
        "and last layers have no entry.",
    )
    metalNonmetalBondLength: float = Field(
        description="Mean nearest-neighbour M-X distance over all M sites, in Å.",
    )
    metalTerminationBondLength: float | None = Field(
        None,
        description="Mean nearest-neighbour T-M distance over all T sites, in Å. "
        "Null for pristine MXenes.",
    )
    spaceGroupSymbol: str = Field(
        description="Hermann-Mauguin symbol of the space group of the periodic "
        f"slab model, determined with spglib (symprec={SYMPREC} Å).",
    )
    spaceGroupNumber: int = Field(
        ge=1,
        le=230,
        description="International number of `spaceGroupSymbol`.",
    )

    @classmethod
    def from_structure(cls, structure: Structure) -> StructureDescriptors:
        """Compute all descriptors from a relaxed slab structure."""
        lattice = structure.lattice
        a_vec, b_vec, c_vec = lattice.matrix
        area = float(np.linalg.norm(np.cross(a_vec, b_vec)))
        height = abs(float(c_vec[2]))

        z = _unwrapped_z(structure)
        layers = _group_layers(structure, z)
        layer_elements = [structure[idx[0]].specie.symbol for idx in layers]
        thickness = float(z.max() - z.min())

        composition = structure.composition
        n_x = sum(amt for el, amt in composition.items() if el.symbol in {"C", "N"})
        n_m = sum(amt for el, amt in composition.items() if el.is_transition_metal)
        if n_x == 0 or n_m == 0:
            raise ValueError("Structure must contain a transition metal and C or N")
        n_fu = n_m - n_x  # M_{n+1}X_n => (n+1) - n = 1 per formula unit

        sga = SpacegroupAnalyzer(structure, symprec=SYMPREC)
        return cls(
            reducedFormula=plain_formula(composition),
            nSites=len(structure),
            a=float(lattice.a),
            b=float(lattice.b),
            gamma=float(lattice.gamma),
            cellArea=area,
            areaPerFormulaUnit=area / n_fu,
            arealMassDensity=float(composition.weight)
            / area
            * _AMU_PER_A2_TO_MG_PER_M2,
            thickness=thickness,
            vacuum=height - thickness,
            layerSequence=layer_elements,
            coordinationSequence=[
                _coordination(structure, layers[i - 1], layers[i + 1])
                for i in range(1, len(layers) - 1)
            ],
            metalNonmetalBondLength=_mean_nn_distance(
                structure, _is_metal, lambda s: s in {"C", "N"}
            ),
            metalTerminationBondLength=_mean_nn_distance(
                structure, lambda s: s in {"F", "O"}, _is_metal
            ),
            spaceGroupSymbol=sga.get_space_group_symbol(),
            spaceGroupNumber=sga.get_space_group_number(),
        )


def _unwrapped_z(structure: Structure) -> np.ndarray:
    """Cartesian z of each site with the slab made contiguous across c."""
    fz = structure.frac_coords[:, 2] % 1.0
    order = np.sort(fz)
    gaps = np.diff(np.append(order, order[0] + 1.0))
    start = order[(int(np.argmax(gaps)) + 1) % len(order)]
    fz = (fz - start) % 1.0
    return fz * structure.lattice.matrix[2, 2]


def _group_layers(structure: Structure, z: np.ndarray) -> list[list[int]]:
    """Group site indices into atomic layers ordered from bottom to top."""
    order = np.argsort(z)
    layers: list[list[int]] = [[int(order[0])]]
    for idx in order[1:]:
        if z[idx] - z[layers[-1][-1]] < LAYER_Z_TOLERANCE:
            layers[-1].append(int(idx))
        else:
            layers.append([int(idx)])
    for layer in layers:
        symbols = {structure[i].specie.symbol for i in layer}
        if len(symbols) != 1:
            zs = sorted(round(float(z[i]), 2) for i in layer)
            raise ValueError(
                f"Mixed-species atomic layer found: {sorted(symbols)} at z = {zs} Å; "
                f"atoms of different elements lie within {LAYER_Z_TOLERANCE} Å "
                "of each other along the normal, so the structure may be "
                "strongly distorted"
            )
    return layers


def _coordination(structure: Structure, below: list[int], above: list[int]) -> str:
    """Return `P` if two layers are eclipsed in-plane, otherwise `O`."""
    ab = structure.lattice.matrix[:2, :2]
    shifts = np.array(list(product((-1, 0, 1), repeat=2))) @ ab
    xy = structure.cart_coords[:, :2]
    for i in below:
        for j in above:
            dists = np.linalg.norm(xy[j] - xy[i] + shifts, axis=1)
            if dists.min() < ECLIPSED_XY_TOLERANCE:
                return "P"
    return "O"


def _mean_nn_distance(structure: Structure, is_center, is_neighbor) -> float | None:
    """Mean distance from each center site to its nearest neighbor site."""
    centers = [i for i, s in enumerate(structure) if is_center(s.specie.symbol)]
    neighbors = [i for i, s in enumerate(structure) if is_neighbor(s.specie.symbol)]
    if not centers or not neighbors:
        return None
    dmat = structure.distance_matrix
    return float(np.mean([dmat[i, neighbors].min() for i in centers]))
