version: '2'
services:
  app:
    image: mpcontribs-app
    environment:
      - MPCONTRIBS_DEBUG="True"
    depends_on:
      - mpdev
    entrypoint: /bin/sh
    command: "-c 'cd /app && \
              sed -i 's@https://materialsproject.org/cas/@http://docker.for.mac.localhost:8001/cas/@' test_site/settings.py && \
              git pull && /wait-for-it.sh mpdev:8000 --timeout=15 --strict -- mpcontribs --debug'"
    ports:
      - 127.0.0.2:5001:5000
  #web:
  #  image: mpcontribs-nginx
  #  ports:
  #    - "80:8080"
  #  volumes:
  #    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
  tunnels:
    image: thywolf/alpine-openssh-client
    entrypoint: ssh
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh/mendel@mac14:/root/.ssh/id_rsa:ro
    command: "-N -oStrictHostKeyChecking=no -oServerAliveInterval=60 \
              -oServerAliveCountMax=2 -4 -t -i /root/.ssh/id_rsa \
              -L*:57001:mongodb01.nersc.gov:27017 \
              -L*:57002:matgen2.lbl.gov:27017 \
              -L*:57003:mongodb03.nersc.gov:27017 \
              -L*:57004:mongodb04.nersc.gov:27017 \
              huck@matgen2.lbl.gov"
  mpdev:
    image: mpdev-app
    entrypoint: /bin/sh
    tty: true
    ports:
      - 8001:8000
    depends_on:
      - tunnels
    command: "-c 'pip3 install -U pymatgen \"Django>=1.11,<1.12\" && \
              grunt compile && python3 manage.py cleanupcas && \
              sed -i 's@https://contribs.materialsproject.org@http://127.0.0.2:5001@' /app/materials_django/settings.py && \
              /wait-for-it.sh tunnels:57001 --timeout=1 --strict -- python3 manage.py gruntserver 0.0.0.0:8000'"
