version: '2'
services:

  app:
    image: mpcontribs-app
    restart: always
    environment:
      - MPCONTRIBS_DEBUG="True"
    depends_on:
      - mp
    entrypoint: /bin/sh
    command: "-c 'cd /app/webtzite && git checkout master && git pull && bower install --allow-root && \
              cd /app/mpcontribs/users && git checkout master && git pull && cd /app && \
              sed -i 's@https://materialsproject.org/cas/@http://docker.for.mac.localhost:8001/cas/@' test_site/settings.py && \
              git pull && python manage.py collectstatic --noinput && \
              /wait-for-it.sh mp:8000 --timeout=30 --strict -- mpcontribs --debug'"
    ports:
      - 127.0.0.2:5001:5000
  #web:
  #  image: mpcontribs-nginx
  #  ports:
  #    - "80:8080"
  #  volumes:
  #    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro

  browser:
    image: selenium/standalone-chrome-debug:3.14.0-iron
    volumes:
      - /dev/shm:/dev/shm

  #mongo:
  #  image: mongo
  #  restart: always
  #  command: --noauth
  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example

  #jupyter:
  #  image: jupyter/base-notebook
  #  command: /usr/local/bin/start-singleuser.sh

  tunnels:
    image: thywolf/alpine-openssh-client
    entrypoint: ssh
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh/mendel@mac14:/root/.ssh/id_rsa:ro
    command: "-N -oStrictHostKeyChecking=no -oServerAliveInterval=60 \
              -oServerAliveCountMax=2 -4 -t -i /root/.ssh/id_rsa \
              -L*:57001:mongodb01.nersc.gov:27017 \
              -L*:57002:matgen2.lbl.gov:27017 \
              -L*:57003:mongodb03.nersc.gov:27017 \
              -L*:57004:mongodb04.nersc.gov:27017 \
              huck@matgen2.lbl.gov"
  mp:
    image: mp-app
    entrypoint: /bin/sh
    tty: true
    ports:
      - 8001:8000
    depends_on:
      - tunnels
    command: "-c 'pip3 install -U pymatgen \"Django>=1.11,<1.12\" && grunt compile && \
              /wait-for-it.sh tunnels:57001 --timeout=1 --strict -- python3 manage.py gruntserver 0.0.0.0:8000'"
