"""One complete row of the optional depth-5 RAC table."""

from pydantic import BaseModel, ConfigDict, StrictFloat


class RacFeatures(BaseModel):
    """264 descriptors in rac5Features, present only for successful results.

    The table is optional for a contribution; a present row must be complete.
    Fields preserve the source descriptor tokens in camelCase. Raw numeric
    values are not rescaled and no common physical unit is asserted.
    """

    model_config = ConfigDict(extra="forbid", allow_inf_nan=False, strict=True)

    racsFunctionGroupDFuncI0All: StrictFloat
    racsFunctionGroupDFuncI1All: StrictFloat
    racsFunctionGroupDFuncI2All: StrictFloat
    racsFunctionGroupDFuncI3All: StrictFloat
    racsFunctionGroupDFuncI4All: StrictFloat
    racsFunctionGroupDFuncI5All: StrictFloat
    racsFunctionGroupDFuncS0All: StrictFloat
    racsFunctionGroupDFuncS1All: StrictFloat
    racsFunctionGroupDFuncS2All: StrictFloat
    racsFunctionGroupDFuncS3All: StrictFloat
    racsFunctionGroupDFuncS4All: StrictFloat
    racsFunctionGroupDFuncS5All: StrictFloat
    racsFunctionGroupDFuncT0All: StrictFloat
    racsFunctionGroupDFuncT1All: StrictFloat
    racsFunctionGroupDFuncT2All: StrictFloat
    racsFunctionGroupDFuncT3All: StrictFloat
    racsFunctionGroupDFuncT4All: StrictFloat
    racsFunctionGroupDFuncT5All: StrictFloat
    racsFunctionGroupDFuncZ0All: StrictFloat
    racsFunctionGroupDFuncZ1All: StrictFloat
    racsFunctionGroupDFuncZ2All: StrictFloat
    racsFunctionGroupDFuncZ3All: StrictFloat
    racsFunctionGroupDFuncZ4All: StrictFloat
    racsFunctionGroupDFuncZ5All: StrictFloat
    racsFunctionGroupDFuncAlpha0All: StrictFloat
    racsFunctionGroupDFuncAlpha1All: StrictFloat
    racsFunctionGroupDFuncAlpha2All: StrictFloat
    racsFunctionGroupDFuncAlpha3All: StrictFloat
    racsFunctionGroupDFuncAlpha4All: StrictFloat
    racsFunctionGroupDFuncAlpha5All: StrictFloat
    racsFunctionGroupDFuncChi0All: StrictFloat
    racsFunctionGroupDFuncChi1All: StrictFloat
    racsFunctionGroupDFuncChi2All: StrictFloat
    racsFunctionGroupDFuncChi3All: StrictFloat
    racsFunctionGroupDFuncChi4All: StrictFloat
    racsFunctionGroupDFuncChi5All: StrictFloat
    racsFunctionGroupFuncI0All: StrictFloat
    racsFunctionGroupFuncI1All: StrictFloat
    racsFunctionGroupFuncI2All: StrictFloat
    racsFunctionGroupFuncI3All: StrictFloat
    racsFunctionGroupFuncI4All: StrictFloat
    racsFunctionGroupFuncI5All: StrictFloat
    racsFunctionGroupFuncS0All: StrictFloat
    racsFunctionGroupFuncS1All: StrictFloat
    racsFunctionGroupFuncS2All: StrictFloat
    racsFunctionGroupFuncS3All: StrictFloat
    racsFunctionGroupFuncS4All: StrictFloat
    racsFunctionGroupFuncS5All: StrictFloat
    racsFunctionGroupFuncT0All: StrictFloat
    racsFunctionGroupFuncT1All: StrictFloat
    racsFunctionGroupFuncT2All: StrictFloat
    racsFunctionGroupFuncT3All: StrictFloat
    racsFunctionGroupFuncT4All: StrictFloat
    racsFunctionGroupFuncT5All: StrictFloat
    racsFunctionGroupFuncZ0All: StrictFloat
    racsFunctionGroupFuncZ1All: StrictFloat
    racsFunctionGroupFuncZ2All: StrictFloat
    racsFunctionGroupFuncZ3All: StrictFloat
    racsFunctionGroupFuncZ4All: StrictFloat
    racsFunctionGroupFuncZ5All: StrictFloat
    racsFunctionGroupFuncAlpha0All: StrictFloat
    racsFunctionGroupFuncAlpha1All: StrictFloat
    racsFunctionGroupFuncAlpha2All: StrictFloat
    racsFunctionGroupFuncAlpha3All: StrictFloat
    racsFunctionGroupFuncAlpha4All: StrictFloat
    racsFunctionGroupFuncAlpha5All: StrictFloat
    racsFunctionGroupFuncChi0All: StrictFloat
    racsFunctionGroupFuncChi1All: StrictFloat
    racsFunctionGroupFuncChi2All: StrictFloat
    racsFunctionGroupFuncChi3All: StrictFloat
    racsFunctionGroupFuncChi4All: StrictFloat
    racsFunctionGroupFuncChi5All: StrictFloat
    racsLinkerDLcI0All: StrictFloat
    racsLinkerDLcI1All: StrictFloat
    racsLinkerDLcI2All: StrictFloat
    racsLinkerDLcI3All: StrictFloat
    racsLinkerDLcI4All: StrictFloat
    racsLinkerDLcI5All: StrictFloat
    racsLinkerDLcS0All: StrictFloat
    racsLinkerDLcS1All: StrictFloat
    racsLinkerDLcS2All: StrictFloat
    racsLinkerDLcS3All: StrictFloat
    racsLinkerDLcS4All: StrictFloat
    racsLinkerDLcS5All: StrictFloat
    racsLinkerDLcT0All: StrictFloat
    racsLinkerDLcT1All: StrictFloat
    racsLinkerDLcT2All: StrictFloat
    racsLinkerDLcT3All: StrictFloat
    racsLinkerDLcT4All: StrictFloat
    racsLinkerDLcT5All: StrictFloat
    racsLinkerDLcZ0All: StrictFloat
    racsLinkerDLcZ1All: StrictFloat
    racsLinkerDLcZ2All: StrictFloat
    racsLinkerDLcZ3All: StrictFloat
    racsLinkerDLcZ4All: StrictFloat
    racsLinkerDLcZ5All: StrictFloat
    racsLinkerDLcAlpha0All: StrictFloat
    racsLinkerDLcAlpha1All: StrictFloat
    racsLinkerDLcAlpha2All: StrictFloat
    racsLinkerDLcAlpha3All: StrictFloat
    racsLinkerDLcAlpha4All: StrictFloat
    racsLinkerDLcAlpha5All: StrictFloat
    racsLinkerDLcChi0All: StrictFloat
    racsLinkerDLcChi1All: StrictFloat
    racsLinkerDLcChi2All: StrictFloat
    racsLinkerDLcChi3All: StrictFloat
    racsLinkerDLcChi4All: StrictFloat
    racsLinkerDLcChi5All: StrictFloat
    racsLinkerFLigI0: StrictFloat
    racsLinkerFLigI1: StrictFloat
    racsLinkerFLigI2: StrictFloat
    racsLinkerFLigI3: StrictFloat
    racsLinkerFLigI4: StrictFloat
    racsLinkerFLigI5: StrictFloat
    racsLinkerFLigS0: StrictFloat
    racsLinkerFLigS1: StrictFloat
    racsLinkerFLigS2: StrictFloat
    racsLinkerFLigS3: StrictFloat
    racsLinkerFLigS4: StrictFloat
    racsLinkerFLigS5: StrictFloat
    racsLinkerFLigT0: StrictFloat
    racsLinkerFLigT1: StrictFloat
    racsLinkerFLigT2: StrictFloat
    racsLinkerFLigT3: StrictFloat
    racsLinkerFLigT4: StrictFloat
    racsLinkerFLigT5: StrictFloat
    racsLinkerFLigZ0: StrictFloat
    racsLinkerFLigZ1: StrictFloat
    racsLinkerFLigZ2: StrictFloat
    racsLinkerFLigZ3: StrictFloat
    racsLinkerFLigZ4: StrictFloat
    racsLinkerFLigZ5: StrictFloat
    racsLinkerFLigChi0: StrictFloat
    racsLinkerFLigChi1: StrictFloat
    racsLinkerFLigChi2: StrictFloat
    racsLinkerFLigChi3: StrictFloat
    racsLinkerFLigChi4: StrictFloat
    racsLinkerFLigChi5: StrictFloat
    racsLinkerLcI0All: StrictFloat
    racsLinkerLcI1All: StrictFloat
    racsLinkerLcI2All: StrictFloat
    racsLinkerLcI3All: StrictFloat
    racsLinkerLcI4All: StrictFloat
    racsLinkerLcI5All: StrictFloat
    racsLinkerLcS0All: StrictFloat
    racsLinkerLcS1All: StrictFloat
    racsLinkerLcS2All: StrictFloat
    racsLinkerLcS3All: StrictFloat
    racsLinkerLcS4All: StrictFloat
    racsLinkerLcS5All: StrictFloat
    racsLinkerLcT0All: StrictFloat
    racsLinkerLcT1All: StrictFloat
    racsLinkerLcT2All: StrictFloat
    racsLinkerLcT3All: StrictFloat
    racsLinkerLcT4All: StrictFloat
    racsLinkerLcT5All: StrictFloat
    racsLinkerLcZ0All: StrictFloat
    racsLinkerLcZ1All: StrictFloat
    racsLinkerLcZ2All: StrictFloat
    racsLinkerLcZ3All: StrictFloat
    racsLinkerLcZ4All: StrictFloat
    racsLinkerLcZ5All: StrictFloat
    racsLinkerLcAlpha0All: StrictFloat
    racsLinkerLcAlpha1All: StrictFloat
    racsLinkerLcAlpha2All: StrictFloat
    racsLinkerLcAlpha3All: StrictFloat
    racsLinkerLcAlpha4All: StrictFloat
    racsLinkerLcAlpha5All: StrictFloat
    racsLinkerLcChi0All: StrictFloat
    racsLinkerLcChi1All: StrictFloat
    racsLinkerLcChi2All: StrictFloat
    racsLinkerLcChi3All: StrictFloat
    racsLinkerLcChi4All: StrictFloat
    racsLinkerLcChi5All: StrictFloat
    racsMetalDMcI0All: StrictFloat
    racsMetalDMcI1All: StrictFloat
    racsMetalDMcI2All: StrictFloat
    racsMetalDMcI3All: StrictFloat
    racsMetalDMcI4All: StrictFloat
    racsMetalDMcI5All: StrictFloat
    racsMetalDMcS0All: StrictFloat
    racsMetalDMcS1All: StrictFloat
    racsMetalDMcS2All: StrictFloat
    racsMetalDMcS3All: StrictFloat
    racsMetalDMcS4All: StrictFloat
    racsMetalDMcS5All: StrictFloat
    racsMetalDMcT0All: StrictFloat
    racsMetalDMcT1All: StrictFloat
    racsMetalDMcT2All: StrictFloat
    racsMetalDMcT3All: StrictFloat
    racsMetalDMcT4All: StrictFloat
    racsMetalDMcT5All: StrictFloat
    racsMetalDMcZ0All: StrictFloat
    racsMetalDMcZ1All: StrictFloat
    racsMetalDMcZ2All: StrictFloat
    racsMetalDMcZ3All: StrictFloat
    racsMetalDMcZ4All: StrictFloat
    racsMetalDMcZ5All: StrictFloat
    racsMetalDMcChi0All: StrictFloat
    racsMetalDMcChi1All: StrictFloat
    racsMetalDMcChi2All: StrictFloat
    racsMetalDMcChi3All: StrictFloat
    racsMetalDMcChi4All: StrictFloat
    racsMetalDMcChi5All: StrictFloat
    racsMetalFI0All: StrictFloat
    racsMetalFI1All: StrictFloat
    racsMetalFI2All: StrictFloat
    racsMetalFI3All: StrictFloat
    racsMetalFI4All: StrictFloat
    racsMetalFI5All: StrictFloat
    racsMetalFS0All: StrictFloat
    racsMetalFS1All: StrictFloat
    racsMetalFS2All: StrictFloat
    racsMetalFS3All: StrictFloat
    racsMetalFS4All: StrictFloat
    racsMetalFS5All: StrictFloat
    racsMetalFT0All: StrictFloat
    racsMetalFT1All: StrictFloat
    racsMetalFT2All: StrictFloat
    racsMetalFT3All: StrictFloat
    racsMetalFT4All: StrictFloat
    racsMetalFT5All: StrictFloat
    racsMetalFZ0All: StrictFloat
    racsMetalFZ1All: StrictFloat
    racsMetalFZ2All: StrictFloat
    racsMetalFZ3All: StrictFloat
    racsMetalFZ4All: StrictFloat
    racsMetalFZ5All: StrictFloat
    racsMetalFChi0All: StrictFloat
    racsMetalFChi1All: StrictFloat
    racsMetalFChi2All: StrictFloat
    racsMetalFChi3All: StrictFloat
    racsMetalFChi4All: StrictFloat
    racsMetalFChi5All: StrictFloat
    racsMetalMcI0All: StrictFloat
    racsMetalMcI1All: StrictFloat
    racsMetalMcI2All: StrictFloat
    racsMetalMcI3All: StrictFloat
    racsMetalMcI4All: StrictFloat
    racsMetalMcI5All: StrictFloat
    racsMetalMcS0All: StrictFloat
    racsMetalMcS1All: StrictFloat
    racsMetalMcS2All: StrictFloat
    racsMetalMcS3All: StrictFloat
    racsMetalMcS4All: StrictFloat
    racsMetalMcS5All: StrictFloat
    racsMetalMcT0All: StrictFloat
    racsMetalMcT1All: StrictFloat
    racsMetalMcT2All: StrictFloat
    racsMetalMcT3All: StrictFloat
    racsMetalMcT4All: StrictFloat
    racsMetalMcT5All: StrictFloat
    racsMetalMcZ0All: StrictFloat
    racsMetalMcZ1All: StrictFloat
    racsMetalMcZ2All: StrictFloat
    racsMetalMcZ3All: StrictFloat
    racsMetalMcZ4All: StrictFloat
    racsMetalMcZ5All: StrictFloat
    racsMetalMcChi0All: StrictFloat
    racsMetalMcChi1All: StrictFloat
    racsMetalMcChi2All: StrictFloat
    racsMetalMcChi3All: StrictFloat
    racsMetalMcChi4All: StrictFloat
    racsMetalMcChi5All: StrictFloat
