#!/bin/bash

set -ex

jupyter serverextension enable --py nbzip --sys-prefix
jupyter nbextension install --user --py nbzip
jupyter nbextension enable --user --py nbzip

git config --global user.email "jovyan@materialsproject.org"

git clone -b dev https://github.com/materialsproject/MPContribs.git
export SETUPTOOLS_SCM_PRETEND_VERSION=1.6.0
cd $HOME/MPContribs &&
    cd mpcontribs-client && pip install -e . && \
    cd ../mpcontribs-io && pip install -e . && \
    cd .. && npm install && \
    mv -v binder/binder.js . && \
    mv -v webpack-binder.config.js webpack.config.js && \
    npm run webpack && \
    mkdir -p $HOME/.jupyter/custom && \
    mv -v dist $HOME/.jupyter/custom/js && \
    mv -v binder/custom.js $HOME/.jupyter/custom/ && \
    mkdir binder/MPContribs && mv -v binder/*.ipynb binder/MPContribs/
