#!/bin/bash

set -ex

export SETUPTOOLS_SCM_PRETEND_VERSION=1.6.0
cd $HOME &&
    cd mpcontribs-client && pip install -e . && \
    cd ../mpcontribs-io && pip install -e . && \
    cd .. && npm install && \
    mv -v binder/binder.js . && \
    mv -v webpack-binder.config.js webpack.config.js && \
    npm run webpack && \
    mkdir $HOME/.jupyter/custom && \
    mv -v dist $HOME/.jupyter/custom/js && \
    mv -v binder/custom.js $HOME/.jupyter/custom/
