#!/bin/bash

set -ex

jupyter serverextension enable --py nbzip --sys-prefix
jupyter nbextension install --user --py nbzip
jupyter nbextension enable --user --py nbzip
jupyter nbextensions_configurator enable --user
jupyter nbextension enable --user skip-traceback/main

git config --global user.email "jovyan@materialsproject.org"

export SETUPTOOLS_SCM_PRETEND_VERSION=dev
cd $HOME &&
    cd mpcontribs-client && pip install --no-cache -e . && \
    cd ../mpcontribs-io && pip install --no-cache -e .
    #&& \
    #cd .. && npm install && npm cache clean --force && npm cache verify && \
    #mv -v binder/binder.js . && \
    #mv -v webpack-binder.config.js webpack.config.js && \
    #npm run webpack && \
    #mkdir -p $HOME/.jupyter/custom && \
    #mv -v dist $HOME/.jupyter/custom/js && \
    #mv -v binder/custom.js $HOME/.jupyter/custom/
