[project]
name = "mpcontribs-serverless"
version = "0.1.0"
description = "lambda function definition for mpcontribs workers"
readme = "README.md"
authors = [
    { name = "Brendan Foley", email = "bfoley@lbl.gov" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
mpcontribs-serverless = "mpcontribs_serverless:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
